use std::collections::HashMap;

/// Comprehensive database of USB Vendor IDs
/// Sources: Device Hunt (devicehunt.com), USB-IF, linux-usb.org
/// Last updated: 2026-02
pub fn get_vendor_database() -> HashMap<&'static str, &'static str> {
    let mut vendors = HashMap::new();

    // 0xxx vendors
    vendors.insert("0003", "Club Mac");
    vendors.insert("0040", "Anyware Corporation");
    vendors.insert("0085", "Boeye Technology");
    vendors.insert("0204", "Chipsbank Microelectronics");
    vendors.insert("0402", "ALi Corp.");
    vendors.insert("0403", "Future Technology Devices International (FTDI)");
    vendors.insert("0409", "NEC Corp.");
    vendors.insert("0411", "BUFFALO");
    vendors.insert("0412", "Award Software International");
    vendors.insert("0418", "AST Research");
    vendors.insert("0420", "Chips and Technologies");
    vendors.insert("0422", "ADI Systems");
    vendors.insert("0428", "Advanced Gravis Computer Tech");
    vendors.insert("0429", "Cirrus Logic");
    vendors.insert("042E", "Acer");
    vendors.insert("0433", "Alps Electric");
    vendors.insert("0438", "Advanced Micro Devices (AMD)");
    vendors.insert("044C", "CCL/ITRI");
    vendors.insert("044E", "Alps Electric");
    vendors.insert("0453", "CMD Technology");
    vendors.insert("0456", "Analog Devices");
    vendors.insert("0459", "Adobe Systems");
    vendors.insert("045E", "Microsoft");
    vendors.insert("0460", "Ace Cad Enterprise");
    vendors.insert("0464", "AMP/Tycoelectronics");
    vendors.insert("0467", "AT&T Paradyne");
    vendors.insert("046A", "Cherry");
    vendors.insert("046B", "American Megatrends (AMI)");
    vendors.insert("046D", "Logitech");
    vendors.insert("046E", "Behavior Tech Computer");
    vendors.insert("0472", "Chicony Electronics");
    vendors.insert("0476", "AESP");
    vendors.insert("0479", "Advanced Peripheral Laboratories");
    vendors.insert("047E", "Agere Systems (Lucent)");
    vendors.insert("0480", "Toshiba");
    vendors.insert("0483", "STMicroelectronics");
    vendors.insert("0486", "ASUS Computers");
    vendors.insert("0488", "Cirque");
    vendors.insert("048C", "Alps Electric Ireland");
    vendors.insert("048D", "Integrated Technology Express");
    vendors.insert("0491", "Capetronic");
    vendors.insert("0498", "Capetronic (Kaohsiung)");
    vendors.insert("049C", "Acer Advanced Labs");
    vendors.insert("04A5", "Acer Peripherals (now BenQ)");
    vendors.insert("04A9", "Canon");
    vendors.insert("04AB", "Chromatic Research");
    vendors.insert("04B4", "Cypress Semiconductor");
    vendors.insert("04CA", "Lite-On Technology");
    vendors.insert("04D2", "Altec Lansing");
    vendors.insert("04E4", "ACC Microelectronics");
    vendors.insert("04E8", "Samsung Electronics");
    vendors.insert("04EA", "Brooktree");
    vendors.insert("04ED", "Annabooks");
    vendors.insert("04F2", "Chicony Electronics");
    vendors.insert("04F9", "Brother Industries");
    vendors.insert("04FB", "Biostar Microtech");
    vendors.insert("0502", "Acer");
    vendors.insert("0506", "3Com");
    vendors.insert("0508", "Clarion");
    vendors.insert("0509", "Aztech Systems");
    vendors.insert("050A", "Cinch Connectors");
    vendors.insert("050B", "Cable System International");
    vendors.insert("050D", "Belkin");
    vendors.insert("0515", "ACTC");
    vendors.insert("0517", "Butterfly Communications");
    vendors.insert("0521", "Airborn Connectors");
    vendors.insert("0522", "Advanced Connectek");
    vendors.insert("0523", "ATEN GmbH");
    vendors.insert("0525", "Netchip Technology");
    vendors.insert("0527", "ALTRA");
    vendors.insert("0528", "ATI Technologies");
    vendors.insert("0529", "Aladdin Knowledge Systems");
    vendors.insert("052C", "Canon Information Systems");
    vendors.insert("052D", "Avid Electronics");
    vendors.insert("0530", "American Microsystems");
    vendors.insert("0533", "Alcatel Mobile Phones");
    vendors.insert("0538", "Caldera International (SCO)");
    vendors.insert("0547", "Anchor Chips");
    vendors.insert("0555", "ANAM S&T");
    vendors.insert("0556", "Asahi Kasei Microsystems");
    vendors.insert("0557", "ATEN International");
    vendors.insert("0559", "Cadence Design Systems");
    vendors.insert("0574", "City University of Hong Kong");
    vendors.insert("0576", "BAFO/Quality Computer Accessories");
    vendors.insert("0587", "America Kotobuki Electronics");
    vendors.insert("0599", "Brilliance Semiconductor");
    vendors.insert("059C", "A-Trend Technology");
    vendors.insert("059D", "Advanced Input Devices");
    vendors.insert("05A3", "ARC International");
    vendors.insert("05A6", "Cisco Systems");
    vendors.insert("05A7", "Bose");
    vendors.insert("05AC", "Apple");
    vendors.insert("05BC", "3G Green Green Globe");
    vendors.insert("05C6", "Qualcomm");
    vendors.insert("05C8", "Cheng Uei Precision (Foxlink)");
    vendors.insert("05D1", "Brainboxes");
    vendors.insert("05D9", "Axiohm Transaction Solutions");
    vendors.insert("05E3", "Genesys Logic");
    vendors.insert("05EC", "COM21");
    vendors.insert("05EF", "AVB");
    vendors.insert("05F0", "Canopus");
    vendors.insert("05F6", "AOC International");
    vendors.insert("05FE", "Chic Technology");
    vendors.insert("0600", "Barco Display Systems");
    vendors.insert("0605", "Anchor C&C");
    vendors.insert("0607", "Bridge Information");
    vendors.insert("0614", "Bio-Rad Laboratories");
    vendors.insert("061C", "Act Labs");
    vendors.insert("0620", "Alaris");
    vendors.insert("0624", "Avocent");
    vendors.insert("0627", "Adomax Technology");
    vendors.insert("0638", "Avision");
    vendors.insert("0639", "Chrontel");
    vendors.insert("0647", "Acton Research");
    vendors.insert("0653", "CNF");
    vendors.insert("0659", "Aethra");
    vendors.insert("0667", "Aiwa");
    vendors.insert("0677", "Aiwa");
    vendors.insert("0678", "ACard Technology");
    vendors.insert("0684", "Actiontec Electronics");
    vendors.insert("0698", "Chuntex (CTX)");
    vendors.insert("069A", "Askey Computer");
    vendors.insert("069F", "Allied Data Technologies");
    vendors.insert("06BD", "AGFA-Gevaert");
    vendors.insert("06BE", "AME Optimedia Technology");
    vendors.insert("06C4", "Bizlink International");
    vendors.insert("06D4", "Cisco Systems");
    vendors.insert("06D6", "Aashima Technology");
    vendors.insert("06E1", "ADS Technologies");
    vendors.insert("06E4", "Alcatel Microelectronics");
    vendors.insert("06F9", "ASYST electronic");
    vendors.insert("06FD", "Boston Acoustics");
    vendors.insert("0703", "Bvtech Industry");
    vendors.insert("0706", "Ariel");
    vendors.insert("0723", "Centillium Communications");
    vendors.insert("0729", "Amitm");
    vendors.insert("0735", "Asuscom Network");
    vendors.insert("073A", "Chaplet Systems");
    vendors.insert("074C", "C-C-C Group");
    vendors.insert("0755", "Aureal Semiconductor");
    vendors.insert("0758", "Carl Zeiss Microscopy");
    vendors.insert("0768", "Camtel Technology");
    vendors.insert("0774", "AmTRAN Technology");
    vendors.insert("0777", "Comda Enterprise");
    vendors.insert("0781", "SanDisk");
    vendors.insert("0783", "C3PO");
    vendors.insert("0792", "Axis Communications");
    vendors.insert("0794", "ABL Electronics");
    vendors.insert("0796", "Certicom");
    vendors.insert("0799", "Altera");
    vendors.insert("079D", "Alfadata Computer");
    vendors.insert("07A4", "Be, Inc.");
    vendors.insert("07A6", "ADMtek");
    vendors.insert("07B8", "AboCom Systems");
    vendors.insert("07BC", "Canon Computer Systems");
    vendors.insert("07C0", "Code Mercenaries");
    vendors.insert("07C5", "APG Cash Drawer");
    vendors.insert("07C8", "B.U.G.");
    vendors.insert("07C9", "Allied Telesyn International");
    vendors.insert("07CA", "AVerMedia Technologies");
    vendors.insert("07CC", "Carry Computer Eng.");
    vendors.insert("07CF", "Casio Computer");
    vendors.insert("07D2", "Aptio Products");
    vendors.insert("07DA", "Arasan Chip Systems");
    vendors.insert("07E1", "Ambient Technologies");
    vendors.insert("07E6", "Allied Cable");
    vendors.insert("07F6", "Circuit Assembly");
    vendors.insert("07F7", "Century");
    vendors.insert("0827", "BroadLogic");
    vendors.insert("0835", "Action Star Enterprise");
    vendors.insert("0840", "Argosy Research");
    vendors.insert("0854", "ActiveWire");
    vendors.insert("0856", "B&B Electronics");
    vendors.insert("085C", "ColorVision");
    vendors.insert("0880", "APT Technologies");
    vendors.insert("0885", "Boca Research");
    vendors.insert("087C", "Adesso/Kbtek America");
    vendors.insert("08BD", "Citizen Watch");
    vendors.insert("08C8", "2Wire");
    vendors.insert("08CA", "Aiptek International");
    vendors.insert("08DD", "Billionton Systems");
    vendors.insert("08EE", "CCSI/Hesso");
    vendors.insert("08FA", "Caere");
    vendors.insert("08FF", "AuthenTec");
    vendors.insert("0909", "Audio-Technica");
    vendors.insert("0910", "Alation Systems");
    vendors.insert("0929", "American Biometric");
    vendors.insert("094D", "Cable Television Laboratories");
    vendors.insert("0956", "BSquare");
    vendors.insert("0957", "Agilent Technologies");
    vendors.insert("0959", "Cologne Chip");
    vendors.insert("0964", "BITRAN");
    vendors.insert("0967", "Acer NeWeb");
    vendors.insert("0968", "Catalyst Enterprises");
    vendors.insert("0976", "Adirondack Wire & Cable");
    vendors.insert("0978", "Beckhoff");
    vendors.insert("097E", "Biopac Systems");
    vendors.insert("097F", "Barun Electronics");
    vendors.insert("0984", "Apricorn");
    vendors.insert("0985", "cab Produkttechnik");
    vendors.insert("09BF", "Auerswald");
    vendors.insert("09C1", "Arris Interactive");
    vendors.insert("09C4", "ACTiSYS");
    vendors.insert("09CA", "BMC Messsysteme");
    vendors.insert("09CE", "City Electronics");
    vendors.insert("09DA", "A4Tech");
    vendors.insert("09DC", "Aimex");
    vendors.insert("09DF", "Addonics Technologies");
    vendors.insert("09E8", "AKAI Professional M.I.");
    vendors.insert("09E9", "Chen-Source");
    vendors.insert("09F5", "AresCom");
    vendors.insert("09F9", "Bay Associates");
    vendors.insert("09FB", "Altera");
    vendors.insert("0A12", "Cambridge Silicon Radio");
    vendors.insert("0A22", "Century Semiconductor USA");
    vendors.insert("0A2C", "AK-Modul-Bus Computer");
    vendors.insert("0A43", "Boca Systems");
    vendors.insert("0A5C", "Broadcom");
    vendors.insert("0A66", "ClearCube Technology");
    vendors.insert("0A68", "Comaide");
    vendors.insert("0A69", "Chroma ate");
    vendors.insert("0A6E", "Benwin");
    vendors.insert("0A81", "Chesen Electronics");
    vendors.insert("0A89", "Aktiv");
    vendors.insert("0A90", "Candy Technology");
    vendors.insert("0A93", "C Technologies AB");
    vendors.insert("0AA9", "Baromtec");
    vendors.insert("0AB0", "Arrow Strong Electronics");
    vendors.insert("0AF7", "B2C2");
    vendors.insert("0B05", "ASUSTek Computer");
    vendors.insert("0B0F", "AVID Technology");
    vendors.insert("0B49", "ASCII");
    vendors.insert("0B51", "Comfort Keyboard");
    vendors.insert("0B52", "Colorado MicroDisplay");
    vendors.insert("0B57", "Beijing HanwangTechnology");
    vendors.insert("0B63", "ADLink Technology");
    vendors.insert("0B69", "CacheVision");
    vendors.insert("0B7D", "Astrodesign");
    vendors.insert("0B89", "Advanced Digital Broadcast");
    vendors.insert("0B95", "ASIX Electronics");
    vendors.insert("0B99", "Audio International");
    vendors.insert("0B9F", "Chippo Technologies");
    vendors.insert("0BB2", "Ambit Microsystems");
    vendors.insert("0BBC", "Assistive Technology");
    vendors.insert("0BD7", "Andrew Pargeter & Associates");
    vendors.insert("0BF6", "Addonics Technologies");
    vendors.insert("0C05", "Appian Graphics");
    vendors.insert("0C08", "Agate");
    vendors.insert("0C09", "Comjet Information System");
    vendors.insert("0C4A", "ALGE-TIMING");
    vendors.insert("0C56", "Billion Bright");
    vendors.insert("0C60", "Apogee Electronics");
    vendors.insert("0C62", "Chant Sincere");
    vendors.insert("0C6A", "ACS");
    vendors.insert("0C8C", "Coactive Networks");
    vendors.insert("0C8E", "Cesscom");
    vendors.insert("0C8F", "Applied Microsystems");
    vendors.insert("0C98", "Berkshire Products");
    vendors.insert("0C9C", "Brand Innovators");
    vendors.insert("0CA5", "BAE Systems Canada");
    vendors.insert("0CA6", "Castles Technology");
    vendors.insert("0CAA", "Allied Telesis");
    vendors.insert("0CAE", "Ascom Business Systems");
    vendors.insert("0CAF", "Buslink");
    vendors.insert("0CB6", "Celestix Networks");
    vendors.insert("0CCA", "Amphenol");
    vendors.insert("0CD4", "Bang Olufsen");
    vendors.insert("0CF5", "Cellink");
    vendors.insert("0CF8", "Clarisys");
    vendors.insert("0CF9", "Central System Research");
    vendors.insert("0D0C", "Astron Electronics");
    vendors.insert("0D13", "BMF");
    vendors.insert("0D14", "Array Comm");
    vendors.insert("0D18", "coaXmedia");
    vendors.insert("0D2F", "Andamiro");
    vendors.insert("0D33", "AirSpeak");
    vendors.insert("0D40", "Ascor");
    vendors.insert("0D4D", "Coherent");
    vendors.insert("0D4E", "Agere Systems Netherland");
    vendors.insert("0D50", "Cleware");
    vendors.insert("0D55", "ASKA Technologies");
    vendors.insert("0D56", "AVLAB Technology");
    vendors.insert("0D67", "Advanet");
    vendors.insert("0D6B", "And-Or Logic");
    vendors.insert("0D7E", "American Computer & Digital Components");
    vendors.insert("0D8B", "Ascom Telecommunications");
    vendors.insert("0D8C", "C-Media Electronics");
    vendors.insert("0D9C", "Chee Chen Hi-Technology");
    vendors.insert("0D9E", "Avaya");
    vendors.insert("0DB4", "Chung Fu Chen Yeh Enterprise");
    vendors.insert("0DB5", "Access IS");
    vendors.insert("0DBC", "A&D Medical");
    vendors.insert("0DC3", "Athena Smartcard Solutions");
    vendors.insert("0DD0", "Access Solutions");
    vendors.insert("0DD5", "California Micro Devices");
    vendors.insert("0DE0", "BD Consumer Healthcare");
    vendors.insert("0E0B", "Amigo Technology");
    vendors.insert("0E2E", "Brady Worldwide");
    vendors.insert("0E35", "3Pea Technologies");
    vendors.insert("0E5A", "Active");
    vendors.insert("0E5C", "Bitland Information Technology");
    vendors.insert("0E79", "Archos");
    vendors.insert("0E82", "Ching Tai Electric Wire & Cable");
    vendors.insert("0E92", "C's Glory Enterprise");
    vendors.insert("0E96", "Aplux Communications");
    vendors.insert("0E98", "Advanced Analogic Technologies");
    vendors.insert("0E9B", "ADTEC");
    vendors.insert("0EA8", "CenDyne");
    vendors.insert("0EC1", "Abit Computer");
    vendors.insert("0EC3", "Axell");
    vendors.insert("0EC4", "Ballracing Developments");
    vendors.insert("0EE2", "AMI Semiconductor");
    vendors.insert("0F0C", "CAS");
    vendors.insert("0F13", "Acetek Technology");
    vendors.insert("0F31", "Chrysalis Development");
    vendors.insert("0F3D", "Airprime");
    vendors.insert("0F55", "AmbiCom");
    vendors.insert("0F62", "Acrox Technologies");
    vendors.insert("0FB9", "AACom");
    vendors.insert("0FBB", "Bitwise Systems");
    vendors.insert("0FC5", "Delcom Engineering");
    vendors.insert("0FED", "Access");
    vendors.insert("0FF7", "CHI SHING Computer Accessories");
    vendors.insert("0FFC", "Clavia DMI");
    vendors.insert("0FFF", "Aopen");

    // 1xxx vendors
    vendors.insert("1005", "Apacer Technology");
    vendors.insert("100A", "AV Chaseway");
    vendors.insert("100B", "Chou Chin Industrial");
    vendors.insert("1029", "Atlantic Coast Telesys");
    vendors.insert("1031", "Comax Technology");
    vendors.insert("1032", "C-One Technology");
    vendors.insert("1044", "Chu Yuen Enterprise");
    vendors.insert("1054", "BMS International Beheer");
    vendors.insert("1065", "CCYU Technology");
    vendors.insert("1083", "Canon Electronics");
    vendors.insert("108A", "Chloride Power Protection");
    vendors.insert("1108", "Brightcom Technologies");
    vendors.insert("1110", "Analog Devices Canada (Allied Telesyn)");
    vendors.insert("113C", "Arin Tech");
    vendors.insert("114D", "Alpha Imaging Technology");
    vendors.insert("1166", "Bantam Interactive Technologies");
    vendors.insert("1168", "BizConn International");
    vendors.insert("1188", "Bloomberg");
    vendors.insert("1189", "Acer Communications & Multimedia");
    vendors.insert("11A0", "Chipcon");
    vendors.insert("11B0", "ATECH FLASH TECHNOLOGY");
    vendors.insert("11C0", "Betop");
    vendors.insert("11F7", "Alcatel");
    vendors.insert("1230", "Chipidea-Microelectronica");
    vendors.insert("1234", "Brain Actuated Technologies");
    vendors.insert("1241", "Belkin");
    vendors.insert("124A", "AirVast");
    vendors.insert("125C", "Apogee");
    vendors.insert("125F", "A-DATA Technology");
    vendors.insert("126C", "Aristocrat Technologies");
    vendors.insert("126D", "Bel Stewart");
    vendors.insert("1293", "Belkin Components");
    vendors.insert("12C4", "Autocue Group");
    vendors.insert("12D7", "BETTER WIRE FACTORY");
    vendors.insert("12D8", "Araneus Information Systems");
    vendors.insert("12FD", "AIN Comm. Technology");
    vendors.insert("1325", "ams AG");
    vendors.insert("1343", "Citizen Systems");
    vendors.insert("136E", "Andor Technology");
    vendors.insert("1371", "CNet Technology");
    vendors.insert("1397", "BEHRINGER International");
    vendors.insert("13AD", "Baltech");
    vendors.insert("13B2", "Alesis");
    vendors.insert("13D1", "A-Max Technology Macao");
    vendors.insert("13D3", "IMC Networks");
    vendors.insert("13DC", "ALEREON");
    vendors.insert("1400", "Axxion Group");
    vendors.insert("1402", "Bowe Bell & Howell");
    vendors.insert("1419", "ABILITY ENTERPRISE");
    vendors.insert("142B", "Arbiter Systems");
    vendors.insert("143C", "Altek Corporation");
    vendors.insert("146B", "BigBen Interactive");
    vendors.insert("14AF", "ATP Electronics");
    vendors.insert("14ED", "Shure");
    vendors.insert("1504", "Bixolon");
    vendors.insert("1514", "Actel");
    vendors.insert("1518", "Cheshire Engineering");
    vendors.insert("1519", "Comneon");
    vendors.insert("1520", "Bitwire");
    vendors.insert("1532", "Razer USA");
    vendors.insert("1570", "ALLTOP TECHNOLOGY");
    vendors.insert("15A4", "Afatech Technologies");
    vendors.insert("15EC", "Belcarra Technologies");
    vendors.insert("1605", "ACCES I/O Products");
    vendors.insert("1614", "Amoi Electronics");
    vendors.insert("1630", "2Wire");
    vendors.insert("1633", "AIM GmbH");
    vendors.insert("162A", "Airgo Networks");
    vendors.insert("164A", "ChipX");
    vendors.insert("166A", "Clipsal");
    vendors.insert("1668", "Actiontec Electronics");
    vendors.insert("1677", "China Huada Integrated Circuit Design (CIDC Group)");
    vendors.insert("168C", "Atheros Communications");
    vendors.insert("1690", "Askey Computer");
    vendors.insert("16D5", "AnyDATA Corporation");
    vendors.insert("16D8", "CMOTECH");
    vendors.insert("170D", "Avnera");
    vendors.insert("1706", "BlueView Technologies");
    vendors.insert("1707", "ARTIMI");
    vendors.insert("1726", "Axesstel");
    vendors.insert("1733", "Cellink Technology");
    vendors.insert("1736", "CANON IMAGING SYSTEM TECHNOLOGIES");
    vendors.insert("1737", "Linksys");
    vendors.insert("1761", "ASUSTek Computer (wrong ID)");
    vendors.insert("1776", "Arowana");
    vendors.insert("1787", "ATI AIB");
    vendors.insert("178E", "ASUSTek Computer (wrong ID)");
    vendors.insert("1809", "Advantech");
    vendors.insert("1871", "Aveo Technology");
    vendors.insert("189F", "3Shape");
    vendors.insert("18C5", "AMIT Technology");
    vendors.insert("18EC", "Arkmicro Technologies");
    vendors.insert("18F8", "Maxxter");
    vendors.insert("1914", "Alco Digital Devices");
    vendors.insert("192F", "Avago Technologies");
    vendors.insert("198F", "Beceem Communications");
    vendors.insert("1990", "Acron Precision Industrial");
    vendors.insert("19A8", "Biforst Technology");
    vendors.insert("19AB", "Bodelin");
    vendors.insert("19B2", "Batronix");
    vendors.insert("19B4", "Celestron");
    vendors.insert("19B5", "B & W Group");
    vendors.insert("19D1", "BYD");
    vendors.insert("1A08", "Bellwood International");
    vendors.insert("1A2C", "China Resource Semico");
    vendors.insert("1A25", "Amphenol East Asia");
    vendors.insert("1A34", "ACRUX");
    vendors.insert("1A36", "Biwin Technology");
    vendors.insert("1A41", "Action Electronics");
    vendors.insert("1A61", "Abbott Diabetes Care");
    vendors.insert("1A79", "Bayer Health Care");
    vendors.insert("1A8D", "BandRich");
    vendors.insert("1AD4", "APS");
    vendors.insert("1AFE", "A. Eberle");
    vendors.insert("1B0E", "BLUTRONICS");
    vendors.insert("1B26", "Cellex Power Products");
    vendors.insert("1B3F", "Generalplus Technology");
    vendors.insert("1B52", "ARH");
    vendors.insert("1B5A", "Chao Zhou Kai Yuan Electric");
    vendors.insert("1B72", "ATERGI TECHNOLOGY");
    vendors.insert("1B80", "Afatech");
    vendors.insert("1B8C", "Altium");
    vendors.insert("1B8E", "Amlogic");
    vendors.insert("1BA6", "Abilis Systems");
    vendors.insert("1BA8", "China Telecommunication Technology Labs");
    vendors.insert("1BC0", "Beijing Senseshield Technology");
    vendors.insert("1BC5", "AVIXE Technology (China)");
    vendors.insert("1BD5", "BG Systems");
    vendors.insert("1C13", "ALECTRONIC LIMITED");
    vendors.insert("1C21", "ADDMM");
    vendors.insert("1C37", "Authorizer Technologies");
    vendors.insert("1C49", "Cherng Weei Technology");
    vendors.insert("1C73", "AMT");
    vendors.insert("1C75", "Arturia");
    vendors.insert("1C82", "Atracsys");
    vendors.insert("1C87", "2N TELEKOMUNIKACE");
    vendors.insert("1C8E", "ASTRON INTERNATIONAL");
    vendors.insert("1C98", "ALPINE ELECTRONICS");
    vendors.insert("1CA0", "ACCARIO");
    vendors.insert("1CCD", "Bodatong Technology (Shenzhen)");
    vendors.insert("1CD4", "adp corporation");
    vendors.insert("1CD6", "Antonio Precise Products");
    vendors.insert("1CE1", "Amphenol KAE");
    vendors.insert("1CFC", "ANDES TECHNOLOGY CORPORATION");
    vendors.insert("1D14", "ALPHA-SAT TECHNOLOGY");
    vendors.insert("1D17", "C-Thru Music");
    vendors.insert("1D27", "ASUS");
    vendors.insert("1D90", "Citizen");
    vendors.insert("1DE1", "Actions Microelectronics");
    vendors.insert("1E3D", "Chipsbank Microelectronics");
    vendors.insert("1E41", "Cleverscope");
    vendors.insert("1E6F", "PDP (Performance Designed Products)");
    vendors.insert("1E71", "NZXT");
    vendors.insert("1E74", "Coby Electronics");
    vendors.insert("1E8E", "Airbus Defence and Space");
    vendors.insert("1EDA", "AirTies Wireless Networks");
    vendors.insert("1EDB", "Blackmagic design");
    vendors.insert("1ECB", "AMTelecom");
    vendors.insert("1F0C", "CMX Systems");
    vendors.insert("1F28", "Cal-Comp");
    vendors.insert("1F3A", "Allwinner Technology");
    vendors.insert("1F6F", "Aliph");
    vendors.insert("1F84", "Alere");

    // 2xxx vendors
    vendors.insert("2000", "CMX Systems");
    vendors.insert("2040", "Hauppauge");
    vendors.insert("2080", "Barnes & Noble");
    vendors.insert("2087", "Cando");
    vendors.insert("2101", "ActionStar");
    vendors.insert("2109", "VIA Labs");
    vendors.insert("2123", "Cheeky Dream");
    vendors.insert("2149", "Advanced Silicon");
    vendors.insert("2162", "Broadxent (Creative Labs)");
    vendors.insert("21B4", "AudioQuest");
    vendors.insert("21D6", "Agecodagis");
    vendors.insert("21F4", "Qualcore Logic");
    vendors.insert("2227", "G-PRO");
    vendors.insert("224F", "APDM");
    vendors.insert("2245", "Aspeed Technology");
    vendors.insert("228D", "8D Technologies");
    vendors.insert("22E8", "Cambridge Audio");
    vendors.insert("2341", "Arduino SA");
    vendors.insert("239A", "Adafruit");
    vendors.insert("2433", "ASETEK");
    vendors.insert("2443", "Aessent Technology");
    vendors.insert("245F", "Chord Electronics");
    vendors.insert("24C0", "Chaney Instrument");
    vendors.insert("24DC", "Aladdin R.D.");
    vendors.insert("24FF", "Acroname");
    vendors.insert("256F", "3Dconnexion");
    vendors.insert("2520", "ANA-U");
    vendors.insert("2554", "ASSA ABLOY");
    vendors.insert("2555", "Basis Science");
    vendors.insert("2574", "AVer Information");
    vendors.insert("2576", "AFO");
    vendors.insert("25A7", "Areson Technology");
    vendors.insert("25BB", "Brunner Elektronik");
    vendors.insert("25C4", "ARCAM");
    vendors.insert("25DD", "Bit4id");
    vendors.insert("2626", "Aruba Networks");
    vendors.insert("2676", "Basler");
    vendors.insert("2685", "Cardo Peripheral Systems");
    vendors.insert("2707", "Bardac Corporation");
    vendors.insert("2730", "Citizen");
    vendors.insert("27BD", "Codethink");
    vendors.insert("27C0", "Cadwell Laboratories");
    vendors.insert("27D4", "Blackstar Amplification");
    vendors.insert("2821", "ASUSTek Computer");
    vendors.insert("2912", "Audioengine");
    vendors.insert("29E7", "Brunel University");
    vendors.insert("29E8", "4Links");
    vendors.insert("29F1", "Canaan Creative");
    vendors.insert("2A6E", "Bare Conductive");
    vendors.insert("2A70", "OnePlus Technology");
    vendors.insert("2AEC", "Ambiq Micro");
    vendors.insert("2B24", "NVIDIA");
    vendors.insert("2C4F", "Canon Electronic Business Machines");
    vendors.insert("2CD9", "Cambrionix");
    vendors.insert("2DC8", "8BitDo");
    vendors.insert("2E8A", "Raspberry Pi");
    vendors.insert("2ECC", "ASR Microelectronics");
    vendors.insert("2FEB", "Beijing Veikk E-Commerce");
    vendors.insert("3016", "Boundary Devices");
    vendors.insert("3037", "Beijing Chushifengmang Technology");
    vendors.insert("30A4", "Blues Wireless");
    vendors.insert("30FA", "Instant Microelectronics");
    vendors.insert("31C9", "BeiJing LanXum Computer Technology");
    vendors.insert("3171", "8086 Consultancy");
    vendors.insert("3200", "Alcatel-Lucent Enterprise");
    vendors.insert("322E", "ZOOM Corporation");
    vendors.insert("3334", "AEI");
    vendors.insert("4317", "Broadcom");
    vendors.insert("4766", "Aceeca");
    vendors.insert("50C2", "Averatec");
    vendors.insert("5332", "Clearly Superior Technologies");
    vendors.insert("5986", "Bison Electronics");
    vendors.insert("6000", "Beholder International");
    vendors.insert("6547", "Arkmicro Technologies");
    vendors.insert("6891", "3Com");
    vendors.insert("7104", "CME (Central Music Co.)");
    vendors.insert("7373", "Beijing STONE Technology");
    vendors.insert("8070", "ACCES I/O Products");
    vendors.insert("8E06", "CH Products");
    vendors.insert("9849", "Bestmedia CD Recordable");
    vendors.insert("9886", "Astro Gaming");
    vendors.insert("A128", "AnMo Electronics / Dino-Lite");
    vendors.insert("A168", "AnMo Electronics");
    vendors.insert("A600", "ASIX s.r.o.");
    vendors.insert("A727", "3Com");
    vendors.insert("A88A", "Clas Ohlsson");
    vendors.insert("AB12", "aplic");
    vendors.insert("BA77", "Clockmaker");
    vendors.insert("C216", "Card Device Expert");
    vendors.insert("C502", "AGPTek");
    vendors.insert("CACE", "CACE Technologies");
    vendors.insert("F3F0", "CCT");
    vendors.insert("F4EC", "Atten Electronics / Siglent Technologies");

    vendors
}

pub fn lookup_vendor(vid: &str) -> Option<String> {
    let vendors = get_vendor_database();
    vendors.get(vid).map(|v| v.to_string())
}

pub fn parse_vid_pid(device_type: &str) -> (Option<String>, Option<String>) {
    let upper = device_type.to_uppercase();

    let vid = if let Some(start) = upper.find("VID_") {
        let vid_str = &upper[start + 4..];
        if let Some(end_pos) = vid_str.find(&['&', '\\'][..]) {
            Some(vid_str[..end_pos].to_string())
        } else if vid_str.len() >= 4 {
            Some(vid_str[..4].to_string())
        } else {
            None
        }
    } else {
        None
    };

    let pid = if let Some(start) = upper.find("PID_") {
        let pid_str = &upper[start + 4..];
        if let Some(end_pos) = pid_str.find(&['&', '\\'][..]) {
            Some(pid_str[..end_pos].to_string())
        } else if pid_str.len() >= 4 {
            Some(pid_str[..4].to_string())
        } else {
            None
        }
    } else {
        None
    };

    (vid, pid)
}
